---
- name: Add ansible repo
  apt_repository:
    repo: ppa:ansible/ansible
    state: present
    update_cache: yes

- name: Update apt
  apt:
    update_cache: true
    cache_valid_time: 600
  ignore_errors: true
  changed_when: false

- name: Install basic packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - ansible
    - ansible-lint