---
- name: Add groups
  group:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ user_groups }}"

- name: Add/remove users
  user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    password: "{{ item.password | password_hash('sha512') }}"
    home: "{{ item.home }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    append: "{{ item.append }}"
    state: "{{ item.state }}"
    force: true
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_ed25519
    ssh_key_type: ed25519
  with_items: "{{ users }}"
  no_log: true
# changed_when: false

- name: Install service ssh keys
  authorized_key:
    user: service
    key: "{{ item.key }}"
    state: "{{ item.state }}"
  with_items: "{{ service_keys }}"
  no_log: true

