---
- name: add groups
  group:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ user_groups }}"

- name: add users
  user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    password: "{{ item.password|password_hash('sha512') }}"
    home: "{{ item.home }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    append: "{{ item.append }}"
    state: "{{ item.state }}"
  with_items: "{{ users }}"
  no_log: true
  #changed_when: false

- name: install service ssh keys
  authorized_key:
    user: service
    key: "{{ item.key }}"
    state: "{{ item.state }}"
  with_items: "{{ service_keys }}"
  no_log: true
