---
- name: Config for all hosts
  hosts: all
  become: true

  roles:
    - { role: upgrade_and_basic_packages,
        tags: 'ub' }
    - { role: firewall_base,
        tags: 'fb'}
    - { role: users_and_keys,
        tags: 'uk' }
