---
# - name: Check if Ubuntu 16.04 LTS
#  fail: msg="ansible_distribution is NOT Ubuntu 16.04 LTS!"
#  when: ansible_distribution != 'Ubuntu' or ansible_distribution_version != '16.04'

# TODO Check for Rasbian

- name: Update apt
  apt:
    update_cache: true
    cache_valid_time: 600
  ignore_errors: true
  changed_when: false

- name: Apt upgrade
  apt:
    upgrade: full

- name: Install basic packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - ntp
    - git
    - mc
    - unzip
    - dstat
    - htop
    - tcptrack
    - fail2ban
    - pipenv
